RENDER_COLUMNS=80

all: README.txt

README.txt: docs/README.txt
	RENDER_COLUMNS=$(RENDER_COLUMNS) COLOR=no ./view.py docs/README.txt > README.txt

README.html: docs/README.txt
	RENDER_COLUMNS=$(RENDER_COLUMNS) RENDERING_MODE=RENDERING_MODE_HTML_ASCII_ART COLOR=no ./view.py docs/README.txt > README.html
